export type Source={type:'plans'|'manual';page:number;label:string};
export type Stage={title:string;short:string;phase:string;action:string;why:string;checks:string[];note:string;sources:Source[];view?:string};
const m=(page:number,label:string):Source=>({type:'manual',page,label});
const p=(page:number,label:string):Source=>({type:'plans',page,label});
export const sourceUrl=(s:Source)=>`/sources/${s.type}.pdf#page=${s.page}`;
export const stages:Stage[]=[
{title:'Start with sound materials',short:'Materials & joins',phase:'PREPARE',action:'Prepare four sheets of marine plywood, framing timber, marine epoxy and glass reinforcement. Join sheets into long blanks for the hull panels.',why:'The forward bottom panels bend and twist substantially. Sound plywood and joints are essential before shaping begins.',checks:['Confirm marine plywood quality and at least 6 mm thickness.','Choose the sheet-joining method and establish a straight measuring datum.','Read the complete sequence before cutting.'],note:'The materials list is an estimate. Follow your epoxy system’s cure instructions; playback time is not workshop time.',sources:[m(1,'Plywood and timber'),m(3,'Scarf joints'),m(9,'Joining alternatives')]},
{title:'Mark and cut matching panels',short:'Cut hull panels',phase:'PREPARE',action:'Mark the hull panels on a 300 mm grid, fair the curves with a batten, cut outside the lines and plane to shape. Trace matching pieces from the first pair.',why:'Matching port and starboard panels help the hull form symmetrically. A straight datum matters more than the edge of a joined sheet.',checks:['Check the grid and datum before marking offsets.','Compare matching panels and fair their edges.','Keep the forefoot corner sharp for assembly; round it later.'],note:'The animated flat shapes are illustrative, not cutting templates. Use the dimensioned plans and original layout.',sources:[p(4,'Panel offsets'),p(5,'Nesting'),m(9,'Marking'),m(10,'Matching panels')]},
{title:'Prepare bulkheads and transom',short:'Prepare frames',phase:'PREPARE',action:'Cut bulkheads 1, 1A, 2, 2A and 3 and the transom. Fit timber frames and cleats on their specified faces. Mark their positions on the hull panels.',why:'These sections establish the hull shape. Framing orientation and temporary cross-braces matter when the panels are wrapped around them.',checks:['Check each frame’s forward and aft faces.','Allow for the specified bevels and check the final fit on the boat.','Provide temporary cross-bracing as described for plan-built construction.'],note:'Timber framing and temporary braces are simplified. This guide follows the ordinary plans, not a pre-cut kit.',sources:[p(6,'Bulkheads 1 / 1A'),p(7,'Bulkheads 2 / 2A'),p(8,'Bulkhead 3'),p(9,'Transom'),m(10,'Framing')]},
{title:'Stitch and open the bottom',short:'Open the bottom',phase:'FORM THE HULL',action:'Drill stitch holes. Lay the bottom panels inner-face to inner-face, loosely stitch the keel edges, and open them like a book into a V.',why:'Slack in the keel ties lets the panels unfold into their rocker. The highly twisted forward region needs closer stitching and careful handling.',checks:['Use the manual’s hole offsets and closer bow spacing.','Leave enough slack for the panels to unfold.','Check the small inner bevels meet without slipping past each other.'],note:'Movement illustrates the sequence; it does not simulate plywood stresses. Do not force the bow to match the animation.',sources:[m(11,'Stitching and unfolding'),p(23,'Panel-edge relationship')]},
{title:'Locate the first bulkheads',short:'Locate bulkheads',phase:'FORM THE HULL',action:'Tie bulkheads 1, 2 and 3 onto their marked positions on the bottom panels. Tie in the transom. Leave 1A and 2A for later.',why:'The main bulkheads establish the cross-sections while the assembly is still adjustable.',checks:['Reference the forward plywood edges at 1 and 2, and the aft edge at 3.','Hold the bulkheads against the bottom panels.','Keep the temporary braces while wrapping the sides.'],note:'Station locations follow the drawing. Transom rake and the fair surfaces between stations are reconstructed.',sources:[p(3,'Station locations'),m(11,'First bulkheads'),m(12,'Reference edges')]},
{title:'Wrap the sides, bow to stern',short:'Wrap the sides',phase:'FORM THE HULL',action:'With a helper, stitch the side panels at the stem, then to the bottom from bow to stern. Lift the aft ends initially and lower them progressively as stitching continues.',why:'The side panels act as levers to establish the bow shape and keel rocker. This order is particularly important on Flint.',checks:['Keep the forward chine stitches tight as described.','Lower the aft ends gradually rather than forcing all edges together.','Join the sides to the transom after working aft.'],note:'Read the illustrated procedure alongside the animation. Many small adjustments are compressed into one transition.',sources:[m(11,'Start the sides'),m(12,'Bow-to-stern procedure')]},
{title:'Complete and align the loose hull',short:'Align the hull',phase:'FORM THE HULL',action:'Add bulkheads 1A and 2A. Adjust the stitches and check symmetry, fairness and twist before gluing anything permanently.',why:'Epoxy locks in the shape you have now. Correct misalignment while the structure can still move.',checks:['Check the 300 mm spacing to 1A and 2A.','Level the transom and bulkheads across the boat.','Check centreline, diagonals and sight lines for symmetry and twist.'],note:'The centreline is a visual aid, not a measuring tool. Refer to the drawing for which bulkhead face defines its station.',sources:[p(3,'Bulkhead spacing'),m(13,'Alignment checks')]},
{title:'Tack, cure, then reinforce inside',short:'Bond the inside',phase:'BOND & REINFORCE',action:'Apply short epoxy tacks between the ties. After cure, remove ties and complete internal fillets and glass reinforcement. Remove temporary braces when the structure supports itself.',why:'Tacks hold alignment while you remove the stitches. Fillets and glass then form the permanent structural joints.',checks:['Recheck alignment before tacking.','Let the tacks cure before removing ties.','Confirm the reinforcement schedule, especially at stem and transom.'],note:'The manual has conflicting glass units and overlap dimensions. Resolve the schedule before laminating. Coloured bands are not tape-width or layer-count specifications.',sources:[m(8,'Glass schedule'),m(13,'Tacking and filleting'),m(14,'Stem reinforcement')]},
{title:'Round and reinforce the exterior',short:'Bond the outside',phase:'BOND & REINFORCE',action:'After cure, turn and support the hull without twist. Round the forefoot and seams, fill voids, then apply the specified external tapes or sheathing.',why:'Rounded transitions let glass follow the seams. Full sheathing is an optional abrasion layer with a weight trade-off.',checks:['Support the overturned hull without distortion.','Fill voids before applying glass.','Avoid resin puddles and sanding through fibres.'],note:'Use the underside view. The boat stays in upright coordinates; the camera moves beneath it. The bands illustrate joint locations only.',sources:[m(14,'Exterior work'),m(15,'Fairing'),p(23,'Seam section')],view:'bottom'},
{title:'Laminate the gunwales evenly',short:'Gunwales',phase:'FIT OUT',action:'Wrap and glue the gunwale laminations on both sides, one layer at a time. Let the first layer cure before fitting the next.',why:'Applying corresponding layers on both sides together balances bending forces and helps prevent distortion.',checks:['Apply each layer to both sides together.','Check that the sheer stays fair while clamping.','Follow the selected section option in the drawing.'],note:'Each side’s two laminations are grouped for selection. An alternative in the plans uses two 19 × 19 mm laminations.',sources:[m(15,'Gunwale assembly'),p(18,'Section options')]},
{title:'Fit corner reinforcement',short:'Corner details',phase:'FIT OUT',action:'Fit the bow breasthook and transom quarter knees. Prepare the towing-eye backing while the forward compartment is accessible.',why:'These local pieces connect hull edges and support fittings. Access becomes limited once the tank is closed.',checks:['Fit bevels to the actual hull.','Check backing and access for the towing fitting.','Seal fitting penetrations according to the selected system.'],note:'The suggested 150 mm sides and 19 mm thickness are starting dimensions. Final shapes are fitted on the boat.',sources:[m(15,'Knees and towing-eye backing')]},
{title:'Prepare seats and enclosed spaces',short:'Before closing',phase:'FIT OUT',action:'Trial-fit the tops and glue their underside stiffeners. Seal the enclosed surfaces and prepare inspection ports before closing the compartments.',why:'This is the last convenient chance to inspect the interior and complete sealing and fitting backing.',checks:['Fit top edges to the actual hull.','Check stiffeners, internal sealing and fitting backing.','Allow coatings to cure and keep inspection openings accessible.'],note:'The tops are lifted to expose their undersides. Their outlines are approximate. Resolve the manual’s differing seat-joint taping guidance.',sources:[p(10,'Tops and stiffeners'),m(15,'Bracing'),m(16,'Sealing and fitting')]},
{title:'Close the seats and tanks',short:'Close compartments',phase:'FIT OUT',action:'Bond the fitted tops to their supports. Notch around framing where required and complete the specified edge fillets and reinforcement.',why:'The tops complete the seats and compartments. Check the concealed work before it disappears from view.',checks:['Confirm the previous stage’s interior work is complete.','Check bonding contact and edge fillets.','Keep inspection ports usable after finishing.'],note:'Hide a top to inspect beneath it. The model does not establish buoyancy or watertightness.',sources:[m(16,'Closing compartments'),p(10,'Top shapes')]},
{title:'Fit the rowing details',short:'Rowing fit-out',phase:'FIT OUT',action:'Position foot braces after a trial sit. Bond the skeg to the prepared exterior and fit the oarlock sockets for the rowing positions.',why:'Rowing geometry needs to suit the rower. The skeg must align with the boat’s centreline.',checks:['Trial the seating, foot support and oar handle clearance.','Prepare the cured hull surface before bonding the skeg.','Check fittings against the plan and actual boat.'],note:'The plan recommends 7½-foot oars; the manual discusses 7-foot oars for non-overlapping handles. Hardware is representative.',sources:[p(3,'Rowing positions'),p(9,'Skeg'),p(11,'Oars'),m(16,'Foot braces'),m(17,'Skeg bonding')]},
{title:'Finish and inspect the boat',short:'Finished boat',phase:'FINISH',action:'Fair and coat the hull following the chosen product system’s instructions. Inspect the finished joints, fittings and compartment access.',why:'Finishing protects the work. Completing the animation is a review point, not evidence that a real boat is ready to launch.',checks:['Follow current preparation, curing and coating instructions.','Inspect joints, sealed edges and fittings.','Verify the real boat’s condition and suitability before use.'],note:'Explore the finished rowing boat. Fair curves, local bevels and fitted parts remain illustrative; the original plans govern construction.',sources:[m(17,'Protection'),m(18,'Finishing'),m(19,'Coating guidance')]}
];
export type Part={id:string;name:string;group:string;stage:number;material:string;description:string;sources:Source[];position?:number;verified:string};
const hull=(id:string,name:string):Part=>({id,name,group:'Hull panels',stage:1,material:'6 mm marine plywood',description:id.startsWith('bottom')?'Bottom panel: loosely stitch the keel and unfold into the V-bottom. The bow twists substantially.':'Topside panel: join at the stem, then work aft while progressively lowering the stern end.',sources:[p(4,'Panel layout'),m(id.startsWith('bottom')?11:12,'Assembly procedure')],verified:'Reconstructed through dimensioned sections. Flat animation is not a cutting template.'});
export const parts:Part[]=[...[-1,1].flatMap(s=>[hull(`bottom${s}`,`${s<0?'Port':'Starboard'} bottom panel`),hull(`side${s}`,`${s<0?'Port':'Starboard'} topside panel`)]),
 ...[{id:'1',x:1.134,page:6},{id:'1A',x:1.434,page:6},{id:'2',x:2.286,page:7},{id:'2A',x:2.586,page:7},{id:'3',x:3.544,page:8}].map(b=>({id:`bhd${b.id}`,name:`Bulkhead ${b.id}`,group:'Bulkheads & transom',stage:2,material:'6 mm plywood + timber framing',position:b.x,description:`${b.id.includes('A')?'Fit after stitching the hull.':'Fit before wrapping the sides.'} Side frames attach to the ${b.id==='1'||b.id==='2'?'forward':'aft'} face.`,sources:[p(b.page,`Bulkhead ${b.id}`),p(3,'Stations')],verified:'Dimensioned section; framing and access details simplified.'})),
 {id:'transom',name:'Transom',group:'Bulkheads & transom',stage:2,material:'6 mm plywood + timber bracing',description:'Stern panel. Check rake, level and reinforcement before bonding. The motor doubler is omitted from this rowing configuration.',sources:[p(9,'Transom'),m(11,'Assembly')],verified:'Dimensioned section; rake reconstructed.'},
 {id:'joints',name:'Inner fillets & glass',group:'Joints & reinforcement',stage:7,material:'Marine epoxy and glass reinforcement',description:'Permanent keel, chine, bulkhead, stem and transom joints. Highlight bands show locations rather than precise laminate dimensions.',sources:[m(8,'Glass schedule'),m(13,'Filleting'),m(14,'Stem')],verified:'Illustrative. Resolve conflicting source units before construction.'},
 {id:'outerglass',name:'Exterior glass reinforcement',group:'Joints & reinforcement',stage:8,material:'External tapes or optional sheathing',description:'Reinforce external joints after rounding. Full sheathing is an alternative with additional weight and abrasion resistance.',sources:[m(14,'Exterior work')],verified:'Illustrative seam bands, not a laminate specification.'},
 ...[-1,1].map(s=>({id:`rail${s}`,name:`${s<0?'Port':'Starboard'} gunwale`,group:'Timber & fittings',stage:9,material:'Two timber laminations',description:'Apply each layer on both sides together to balance the bending forces.',sources:[p(18,'Sections'),m(15,'Assembly')],verified:'Simplified section; follow the chosen plan option.'})),
 {id:'corners',name:'Breasthook & quarter knees',group:'Timber & fittings',stage:10,material:'Approximately 19 mm stock',description:'Fitted corner reinforcement at bow and transom, with representative towing-eye backing.',sources:[m(15,'Corner details')],verified:'Approximate fitted geometry.'},
 {id:'supports',name:'Seat & tank-top stiffeners',group:'Seats & compartments',stage:11,material:'38 × 16 mm timber, or similar',description:'Bond to the undersides before installing the tops. Shown travelling with the tops during closure.',sources:[p(10,'Underside bracing'),m(15,'Stiffeners')],verified:'Representative spacing and fitted lengths.'},
 ...[{id:'foretop',name:'Forward tank top'},{id:'foreseat',name:'Forward thwart'},{id:'mainseat',name:'Main rowing thwart'},{id:'afttop',name:'Aft tank top'}].map(t=>({...t,group:'Seats & compartments',stage:11,material:'6 mm plywood with underside bracing',description:'Fit to the real hull. Complete underside work and internal sealing before bonding. Shown lifted in the preparation stage.',sources:[p(10,'Tops and bracing'),m(16,'Fitting')],verified:'Approximate source pattern; requires fitting.'})),
 {id:'ports',name:'Inspection-port covers',group:'Seats & compartments',stage:12,material:'Three purchased screw-in inspection ports',description:'Covers for the inspection openings in bulkheads 1A, 2A and 3. Keep them accessible for inspection and use the fitting manufacturer’s installation instructions.',sources:[p(6,'Forward compartment'),p(7,'Main compartment'),p(8,'Aft compartment'),m(16,'Enclosed spaces')],verified:'Representative fittings; the original materials list specifies three 4-inch ports.'},
 {id:'skeg',name:'Skeg',group:'Timber & fittings',stage:13,material:'19 mm timber',description:'Aft centreline fin. Key the cured hull surface, then bond with thickened epoxy and edge fillets.',sources:[p(9,'Skeg offsets'),m(17,'Bonding')],verified:'Offset-based profile; fitted edge approximate.'},
 {id:'feet',name:'Foot braces',group:'Timber & fittings',stage:13,material:'19 × 19 mm timber',description:'Position after a trial sit. Locations shown in the plan are suggestions.',sources:[p(3,'Suggested locations'),m(16,'Trial sit')],verified:'Suggested position, not a personal fit.'},
 {id:'oarlocks',name:'Oarlock sockets',group:'Timber & fittings',stage:13,material:'Purchased rowing fittings',description:'Two pairs of side-mounted sockets are listed in the materials sheet. Mount suitable fittings using their instructions.',sources:[p(3,'Rowing layout'),m(19,'Oars')],verified:'Representative hardware, not a fabrication drawing.'}
];
