'use client';
import {useState,useRef,useEffect,useCallback} from 'react';
import {BoatViewer,type ViewerHandle} from './BoatViewer';
import {closureSteps,closurePose} from './closure';
import {publicEdition} from './edition';
import {useBoatTools} from './use-boat-tools';
import {stages,parts,sourceUrl,type Source} from './build-data';
import {Button} from '@/components/ui/button';
import {Slider} from '@/components/ui/slider';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Checkbox} from '@/components/ui/checkbox';
import {Switch} from '@/components/ui/switch';
import {SidebarProvider,Sidebar,SidebarContent} from '@/components/ui/sidebar';
import {Input} from '@/components/ui/input';
import {Sailboat,Play,Pause,SkipBack,SkipForward,RotateCcw,Search,Eye,EyeOff,Focus,Layers,BookOpen,ArrowUpRight,ChevronRight,Check,Info,Box,Maximize,Flag,MousePointer2,X} from 'lucide-react';
const installedAt=(id:string)=>id.startsWith('side')?5:id.startsWith('bottom')?3:id.startsWith('bhd')?(id.includes('A')?6:4):id==='transom'?4:['foretop','foreseat','mainseat','afttop','supports'].includes(id)?12:parts.find(p=>p.id===id)?.stage??0;
function Sources({items}:{items:Source[]}){return <div className="source-links">{items.map((s,i)=>publicEdition?<div className="source-reference" key={`${s.type}-${s.page}-${i}`}><BookOpen size={15}/><span>{s.label}<small>{s.type==='plans'?'Plans':'Manual'} · page {s.page} · original pack</small></span></div>:<a key={`${s.type}-${s.page}-${i}`} href={sourceUrl(s)} target="_blank" rel="noreferrer"><BookOpen size={15}/><span>{s.label}<small>{s.type==='plans'?'Plans':'Manual'} · page {s.page}</small></span><ArrowUpRight size={15}/></a>)}</div>}
export default function Home(){
 const [stage,setStage]=useState(0),[playing,setPlaying]=useState(false),[speed,setSpeed]=useState(1),[selected,setSelected]=useState<string|null>(null),[fade,setFade]=useState(false),[isolate,setIsolate]=useState(false),[explode,setExplode]=useState(0),[labels,setLabels]=useState(false),[hidden,setHidden]=useState<Set<string>>(new Set()),[query,setQuery]=useState(''),[leftTab,setLeftTab]=useState('stages'),[rightTab,setRightTab]=useState('guide'),[checks,setChecks]=useState<Set<string>>(new Set()),[pauseChecks,setPauseChecks]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState(''),[view,setView]=useState('iso');
 const [solid,setSolid]=useState(false),[closure,setClosure]=useState<number|null>(null),[detailPlaying,setDetailPlaying]=useState(false),[guided,setGuided]=useState(true);
 const detailStep=closure===null?0:closurePose(closure).step;
 const viewer=useRef<ViewerHandle>(null),stageList=useRef<HTMLDivElement>(null),viewport=useRef<HTMLDivElement>(null);
 const go=useCallback((n:number,auto=false)=>{n=Math.max(0,Math.min(stages.length-1,n));setClosure(null);setDetailPlaying(false);setStage(n);if(!auto)setPlaying(false);setNotice('');setIsolate(false);setSelected(null);setHidden(new Set());setExplode(0);setRightTab('guide');const nextView=stages[n].view??'iso';setView(nextView);viewer.current?.view(nextView);},[]);
 const choose=useCallback((id:string|null)=>{setSelected(id);setRightTab(id?'part':'guide');setPlaying(false);setDetailPlaying(false);setIsolate(false);},[]);
 useEffect(()=>{if(!playing)return;const timer=setTimeout(()=>{if(stage===stages.length-1){setPlaying(false);setNotice('Sequence complete. Explore the boat or replay from the beginning.');return;}const next=stage+1;go(next,true);if(pauseChecks&&[6,11].includes(next)){setPlaying(false);setNotice('Paused at an important check. Review the guide, then press Play to continue.');}},7500/speed);return()=>clearTimeout(timer);},[playing,stage,speed,pauseChecks,go]);
 useEffect(()=>{stageList.current?.querySelector('[aria-current="step"]')?.scrollIntoView({block:'nearest',behavior:'smooth'});},[stage]);
 useEffect(()=>{if(!detailPlaying)return;let raf=0,last=performance.now();const tick=(now:number)=>{const elapsed=Math.min(.1,(now-last)/1000);last=now;setClosure(p=>Math.min(1,(p??0)+elapsed/18));raf=requestAnimationFrame(tick);};raf=requestAnimationFrame(tick);return()=>cancelAnimationFrame(raf);},[detailPlaying]);
 useEffect(()=>{if(closure===1)setDetailPlaying(false);},[closure]);
 useEffect(()=>{if(closure===null||!guided||!detailPlaying)return;const shot=closureSteps[detailStep];viewer.current?.view(shot.view);setView(shot.view);},[detailStep,guided,detailPlaying,closure===null]);
 const startDetail=()=>{go(11);setClosure(0);setFade(true);setGuided(true);setView('compartment');viewer.current?.view('compartment');};
 const detailJump=(value:number)=>{setDetailPlaying(false);setClosure(value);setSelected(null);setIsolate(false);setHidden(new Set());setRightTab('guide');if(guided){const shot=closureSteps[closurePose(value).step];setView(shot.view);viewer.current?.view(shot.view);}};
 const toggleHidden=(id:string)=>setHidden(s=>{const n=new Set(s);n.has(id)?n.delete(id):n.add(id);return n});
 const part=parts.find(p=>p.id===selected),s=stages[stage];const filtered=parts.filter(p=>`${p.name} ${p.group} ${p.material} ${p.id}`.toLowerCase().includes(query.toLowerCase().trim()));
 const ready=parts.filter(p=>p.stage<=stage).length;
 useBoatTools({stage,selected,playing,hidden:[...hidden]},{go,select:choose});
 return <div className="app-shell">
 <header className="masthead"><div className="brand"><span className="brand-symbol"><Sailboat size={25}/></span><div><strong>FLINT<span> / </span><em>build companion</em></strong><small>Ross Lillistone · rowing configuration</small></div></div><div className="header-middle"><span className="live-dot"/> WORKSHOP EDITION</div><div className="header-actions"><Button variant="outline" onClick={startDetail}>Explore compartment closure</Button><Button variant="outline" onClick={()=>setRightTab('sources')}><BookOpen/> Plans & notes</Button></div></header>
 <SidebarProvider className="workspace">
 <Sidebar collapsible="none" className="left-panel"><Tabs value={leftTab} onValueChange={v=>setLeftTab(String(v))} className="left-tabs"><TabsList className="tab-bar"><TabsTrigger value="stages">Build sequence</TabsTrigger><TabsTrigger value="parts">Find a part</TabsTrigger></TabsList>
 <TabsContent value="stages" className="stage-tab"><div className="sidebar-caption"><span>15 stages</span><span>Start → finish</span></div><SidebarContent ref={stageList} className="stage-list">{stages.map((item,i)=><div key={item.short}>{(i===0||item.phase!==stages[i-1].phase)&&<div className="phase-label">{item.phase}</div>}<button className={`stage-item ${stage===i?'active':''}`} aria-current={stage===i?'step':undefined} onClick={()=>go(i)}><span className={`step-number ${i<stage?'past':''}`}>{String(i+1).padStart(2,'0')}</span><span>{item.short}</span>{i===stage&&<ChevronRight size={15}/>}</button></div>)}</SidebarContent><div className="sidebar-foot"><Flag size={15}/><span>Viewing progress, not a record<br/>of completed workshop work.</span></div></TabsContent>
 <TabsContent value="parts" className="parts-tab"><div className="search-wrap"><Search size={16}/><Input placeholder="Search parts or materials…" aria-label="Search boat parts" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="sidebar-caption"><span>{filtered.length} components / groups</span></div><div className="part-list">{filtered.length===0?<p className="empty">No matching parts. Try “bulkhead”, “tank” or “plywood”.</p>:filtered.map((p,i)=><div key={p.id}>{(i===0||p.group!==filtered[i-1].group)&&<div className="phase-label">{p.group}</div>}<div className={`part-row ${p.id===selected?'active':''}`}><button onClick={()=>choose(p.id)}><span className={`part-dot ${p.stage>stage?'future':''}`}/><span>{p.name}<small>{p.stage>stage?`Appears at stage ${p.stage+1}`:hidden.has(p.id)?'Hidden':'In this stage'}</small></span></button><button aria-label={`${hidden.has(p.id)?'Show':'Hide'} ${p.name}`} onClick={()=>toggleHidden(p.id)} disabled={p.stage>stage}>{hidden.has(p.id)?<EyeOff size={15}/>:<Eye size={15}/>}</button></div></div>)}</div>{hidden.size>0&&<Button variant="outline" onClick={()=>setHidden(new Set())}>Show all hidden parts ({hidden.size})</Button>}</TabsContent>
 </Tabs></Sidebar>
 <main className="center-panel"><div className="viewer" ref={viewport}>
 <div className="viewer-title"><div><span className="eyebrow">{s.phase} <span>/ {String(stage+1).padStart(2,'0')}</span></span><h1>{s.title}</h1></div><Button variant="ghost" size="icon" aria-label="Fullscreen model" onClick={()=>{if(document.fullscreenElement)document.exitFullscreen();else viewport.current?.requestFullscreen().catch(()=>setNotice('Fullscreen is unavailable in this browser.'));}}><Maximize/></Button></div>
 <BoatViewer ref={viewer} stage={stage} selected={selected} onSelect={choose} hidden={hidden} fade={fade} isolate={isolate} explode={explode} labels={labels} solid={solid} closure={closure} onError={setError}/>
 {error&&<div className="model-error" role="alert"><Info/>{error}</div>}
 <div className="camera-controls" aria-label="Camera views">{[['iso','3D'],['top','Top'],['side','Side'],['bow','Bow'],['bottom','Under']].map(([id,label])=><button key={id} className={view===id?'active':''} aria-pressed={view===id} onClick={()=>{viewer.current?.view(id);setView(id);setGuided(false)}}>{label}</button>)}<button title="Fit whole model" aria-label="Fit whole model" onClick={()=>{viewer.current?.view('iso');setView('iso')}}><Focus size={16}/></button></div>
 <div className="viewer-options"><label><Switch checked={solid} onCheckedChange={setSolid} size="sm"/>Plain geometry</label><label><Switch checked={fade} onCheckedChange={setFade} size="sm"/>Fade hull</label><label><Switch checked={labels} onCheckedChange={setLabels} size="sm"/>Part labels</label><div className="explode-control"><Layers size={15}/><label id="explode-label">Separate parts</label><Slider aria-labelledby="explode-label" min={0} max={1} step={.01} value={[explode]} onValueChange={v=>setExplode(Array.isArray(v)?v[0]:v)}/></div></div>
 <div className="viewer-bottom"><span><MousePointer2 size={14}/> Drag to orbit · scroll to zoom · click a part</span><span><i className="wood-dot"/> Plywood & timber <i className="glass-dot"/> Joint reinforcement</span></div>
 {selected&&<div className="selection-badge"><Box size={15}/><span>{part?.name}</span><button aria-label="Clear selected part" onClick={()=>choose(null)}><X size={14}/></button></div>}
 </div>
 {closure!==null&&<section className="closure-player" aria-label="Compartment closure demonstration">
 <div className="closure-heading"><span>AFT COMPARTMENT · DETAIL STUDY</span><button aria-label="Exit compartment demonstration" onClick={()=>{setClosure(null);setDetailPlaying(false);setSelected(null);setIsolate(false);setFade(false);setView('iso');viewer.current?.view('iso')}}><X size={16}/></button></div>
 <div className="closure-steps">{closureSteps.map((step,i)=><button key={step.label} aria-current={detailStep===i?'step':undefined} onClick={()=>detailJump(step.at)}><span>{i+1}</span>{step.label}</button>)}</div>
 <p role="status">{closureSteps[detailStep].text}</p>
 <div className="closure-controls"><Button onClick={()=>{setPlaying(false);setSelected(null);setIsolate(false);setHidden(new Set());if(closure===1)setClosure(0);setDetailPlaying(!detailPlaying)}}>{detailPlaying?<Pause size={16}/>:<Play size={16}/>} {detailPlaying?'Pause detail':closure===1?'Replay closure':'Play closure'}</Button><Slider aria-label="Compartment closure progress" min={0} max={1} step={.01} value={[closure]} onValueChange={v=>detailJump(Array.isArray(v)?v[0]:v)}/><label><Switch size="sm" checked={guided} onCheckedChange={setGuided}/>Guide camera</label></div>
 </section>}
 <div className="transport"><div className="transport-top"><div className="playback"><Button variant="ghost" size="icon" aria-label="Restart sequence" onClick={()=>go(0)}><RotateCcw/></Button><Button variant="ghost" size="icon" aria-label="Previous stage" disabled={stage===0} onClick={()=>go(stage-1)}><SkipBack/></Button><Button className="play-button" aria-label={playing?'Pause build':'Play build'} onClick={()=>{setClosure(null);setDetailPlaying(false);if(stage===14){go(0);setPlaying(true);}else setPlaying(!playing);setNotice('')}}>{playing?<Pause size={18}/>:<Play size={18}/>} {playing?'Pause':'Play build'}</Button><Button variant="ghost" size="icon" aria-label="Next stage" disabled={stage===14} onClick={()=>go(stage+1)}><SkipForward/></Button></div><div className="play-settings"><label><Switch size="sm" checked={pauseChecks} onCheckedChange={setPauseChecks}/>Pause at key checks</label><div className="speed-buttons" aria-label="Playback speed">{[.5,1,2].map(v=><button key={v} aria-pressed={speed===v} className={speed===v?'active':''} onClick={()=>setSpeed(v)}>{v}×</button>)}</div></div></div>
 <div className="timeline"><span>{String(stage+1).padStart(2,'0')}<small> / 15</small></span><Slider aria-label="Construction stage" min={0} max={14} step={1} value={[stage]} onValueChange={v=>go(Array.isArray(v)?v[0]:v)}/><button onClick={()=>go(14)}>See finished boat <ChevronRight size={14}/></button></div><div className="transport-note" role="status">{notice||'Explore each stage at your own pace. Playback illustrates order, not working or curing time.'}</div></div>
 </main>
 <aside className="inspector"><Tabs value={rightTab} onValueChange={v=>setRightTab(String(v))}><TabsList className="tab-bar"><TabsTrigger value="guide">Stage guide</TabsTrigger><TabsTrigger value="part">Part details</TabsTrigger><TabsTrigger value="sources">Sources</TabsTrigger></TabsList>
 <TabsContent value="guide" className="inspector-scroll"><div className="guide-index">STAGE {String(stage+1).padStart(2,'0')} <span>OF 15</span></div><h2>{s.title}</h2><p className="guide-action">{s.action}</p>{[11,12].includes(stage)&&<section className="detail-guide"><h3>Look inside before closing</h3>{closure===null?<Button onClick={startDetail}>Explore the closure</Button>:<><p>Follow the four views below the model, or select a component here.</p><div className="detail-parts">{[['afttop','Aft tank top'],['supports','Underside stiffeners'],['bhd3','Bulkhead & opening'],['joints','Internal joints']].map(([id,label])=><Button key={id} variant="outline" onClick={()=>{choose(id);setFade(true);setView(id==='supports'?'underside':'compartment');viewer.current?.view(id==='supports'?'underside':'compartment')}}>{label}</Button>)}</div><p className="quiet">Lifted tops are an inspection view. This is not a hinged lid or a curing-time simulation. Edge stripes show thickness, not a specified ply count.</p></>}</section>}<section className="why-box"><h3>Why this comes now</h3><p>{s.why}</p></section><section className="checks"><div className="section-heading"><h3>Before moving on</h3><span>{s.checks.filter((_,i)=>checks.has(`${stage}-${i}`)).length}/{s.checks.length}</span></div>{s.checks.map((c,i)=><label key={`${stage}-${i}`} className={checks.has(`${stage}-${i}`)?'checked':''}><Checkbox checked={checks.has(`${stage}-${i}`)} onCheckedChange={v=>setChecks(old=>{const n=new Set(old);v?n.add(`${stage}-${i}`):n.delete(`${stage}-${i}`);return n})}/><span>{c}</span></label>)}<small>Reading checks only · reset when the page reloads.</small></section><div className="guide-note"><Info size={16}/><p>{s.note}</p></div><h3 className="sources-heading">From the original instructions</h3><Sources items={s.sources}/></TabsContent>
 <TabsContent value="part" className="inspector-scroll">{part?<><div className="guide-index">{part.group}</div><h2>{part.name}</h2><div className="material-tag">{part.material}</div><p>{part.description}</p>{part.position!==undefined&&<div className="dimension"><strong>{Math.round(part.position*1000)}<small> mm</small></strong><span>station from bow datum · plan p3</span></div>}<div className="part-actions"><Button onClick={()=>{if(stage<installedAt(part.id)&&!(closure!==null&&part.stage<=11))go(installedAt(part.id));setSelected(part.id);setRightTab('part');setHidden(old=>{const n=new Set(old);n.delete(part.id);return n});setFade(true);setTimeout(()=>viewer.current?.focus(),600);}}> <Focus/>Focus part</Button><Button variant="outline" onClick={()=>{if(stage<installedAt(part.id)&&!(closure!==null&&part.stage<=11))go(installedAt(part.id));setSelected(part.id);setRightTab('part');setIsolate(!isolate);setHidden(old=>{const n=new Set(old);n.delete(part.id);return n})}}><Box/>{isolate?'Show context':'Isolate'}</Button><Button variant="outline" onClick={()=>toggleHidden(part.id)}>{hidden.has(part.id)?<Eye/>:<EyeOff/>}{hidden.has(part.id)?'Show':'Hide'}</Button></div><Button variant="ghost" className="jump-button" onClick={()=>{go(installedAt(part.id));setSelected(part.id);setRightTab('part')}}>See installed · stage {installedAt(part.id)+1}<ChevronRight/></Button><div className="guide-note"><Info size={16}/><p>{part.verified}</p></div><Sources items={part.sources}/></>:<div className="empty-detail"><MousePointer2 size={30}/><h2>Get to know a part</h2><p>Click the boat or use “Find a part” to see its material, connections and source drawing.</p><Button variant="outline" onClick={()=>setLeftTab('parts')}><Search/>Find a part</Button></div>}</TabsContent>
 <TabsContent value="sources" className="inspector-scroll"><div className="guide-index">SOURCE LIBRARY</div><h2>Built from your plans</h2><p>This companion explains the rowing configuration of Ross Lillistone’s Flint. Use the original drawings for dimensions and construction details.</p><Sources items={[{type:'plans',page:3,label:'Hull plan, profile & bodyplan'},{type:'plans',page:4,label:'Dimensioned panel layout'},{type:'manual',page:9,label:'Start of assembly sequence'},{type:'manual',page:1,label:'Complete assembly manual'}]}/>{publicEdition?<section className="why-box"><h3>Use your original plan pack</h3><p>References point to the November 2019 Flint plans and assembly manual. The purchased PDFs, drawing files and materials sheet are not distributed with this public guide.</p></section>:<><a className="library-link" href="/sources/panel-layout.png" target="_blank" rel="noreferrer">DXF layout overview <ArrowUpRight size={16}/></a><a className="library-link" href="/sources/materials.gif" target="_blank" rel="noreferrer">Original materials estimate <ArrowUpRight size={16}/></a></>}<section className="why-box"><h3>What is reconstructed?</h3><p>Bulkhead stations and principal sections follow the metric drawings. Hull curves between stations, panel movement, fitted tops, framing bevels and hardware are illustrative.</p></section><h3>Clarifications before construction</h3><ul className="source-cautions"><li>Manual p8: conflicting glass weight units in the stem/transom table.</li><li>Manual p14: “100 mm / 2 inches” overlap is inconsistent.</li><li>Manual pp8 and 16 differ on seat-top joint reinforcement.</li><li>Tank and seat tops must be fitted to the actual hull.</li></ul><p className="quiet">There is no sailing rig or motor in this version. The guide does not validate structural adequacy, buoyancy, a cutting file or launch readiness.</p></TabsContent>
 </Tabs></aside>
 </SidebarProvider><footer className="app-footer"><span>FLINT / ROWING BOAT</span><span>{ready} component groups introduced · {hidden.size} hidden</span><span>{publicEdition?'Source references: November 2019 · Public guide':'Source pack: November 2019 · Private local guide'}</span></footer>
 </div>
}
